### ISSUE TITLE
mod interaction affecting players not getting teleported (1.12)

### ISSUE THREAD

**Issue by SDUBZ** [blay09/ForgivingVoid#1]
players dont get sent to their auto created islands with forgiving void is used with void island control

Forge: 1.12- 2415
forgiving void: ForgivingVoid_1.12-1.0.1.jar
void island control: voidislandcontrol-1.2.4

**Comment by BlayTheNinth** [comment]
I'm not familiar with that mod. What happens normally when you fall into the void there?

Forgiving Void literally just puts you above where you fell, it doesn't get you to spawn or anything.

**Comment by SDUBZ** [comment]
well the bedrock structure you stand to create island is near void and the forgiving void sees it as hey player is in void save them basically

**Comment by BlayTheNinth** [comment]
The bedrock platform spawned at level 86 for me and even if it was a slab at the very bottom of the world, Forgiving Void didn't trigger. It triggers once your feet are below zero. 

However, since you don't actually receive void damage until you're below level -64, I changed it to trigger at -32 instead (and made it an option). That should allow you to fly below void platforms as well, as long as you don't go too deep.
