### ISSUE TITLE
[Request] Option for the void to spawn you in the nether instead of making you fall from the sky

### ISSUE THREAD

**Issue by The-Fireplace** [blay09/ForgivingVoid#3]
Imagine, falling into the void, and you appear in the nether, where you must then figure out how to escape. Not as friendly as falling from the sky, but better than all of your stuff being lost in the void from death.

**Comment by BlayTheNinth** [comment]
You're missing the entire "figure out how to escape" part. I don't think there is any way to get Obsidian for a portal in the Nether, and even if it does exist in loot chests, it would be a huge pain to actually find that. Not the goal of this mod.

**Comment by The-Fireplace** [comment]
Good point.

**Comment by egshels** [comment]
Hate to necro a 7 year old issue, but I think this might actually be a pretty good idea, since there *are* situations where you can fall into the Nether void. 
I'm currently making a 1.20.1 server/modpack with floating island style worldgen, and being able to configure the destination dimension would mean I can make falling into the Overworld void put you in the Nether, and falling into the Nether void put you back in the Overworld, like an infinite dimension stack.
There's a small mod out there that advertises exactly this - Forgiving World - but it's really buggy and inconsistent and the author doesn't seem to be checking issues. It also lacks many of this mod's features.
