### ISSUE TITLE
Add another type of fall damage to be "non-reducible" or "true damage"

### ISSUE THREAD

**Issue by ZiLenTz** [blay09/ForgivingVoid#45]
**Suggestion**
Fall damage from this mod should be (configurable) constant and not reduced by armor or damage reduction enchantment.
Otherwise it would be negligible to properly equipped players.
Also, instead of specifying the amount of damage, changing it to percentage would allow more applications from this mod as well.

**Why?**
Originally when creating a server with floating island world type to play with friends, the idea was to make falling to void to be a bit _forgiving_.
By setting fall damage to 19, players would have a second chance with 1 HP left assuming they were at full HP.

However, after players started to have proper equipment, **this mechanic was exploited** as fall damage got significantly reduced by various types of damage reduction.
(Only damage reduction from vanilla armors and enchantments are enough to reduce it to only 1-2 damage.)
Basically, players just jumped and kelp falling to the void until they finally reached the next island and didn't need to worry about immediate danger that they would have to face right away.

Increasing the damage number (e.g. to 100+ damage) could result in similar net damage, but it would be an instant death to newly joined players and poorly equipped players.

**Comment by BlayTheNinth** [comment]
v21.3.2 adds `fallThroughVoidEffects` and `returnToLastGrounded` options to allow for more control over the mod. Specifically  `returnToLastGrounded` should be able to prevent players from abusing Forgiving Void to travel over larger distances.

I'd rather not add a new damage type for now since it would add new complexity without solving the underlying issue of falling being abused to travel large distances.
