### ISSUE TITLE
[Request] Simple balance idea

### ISSUE THREAD

**Issue by MysticAura** [blay09/ForgivingVoid#6]
This mod is a great idea, but I'm sure there are many who would think it's unfair or the dreaded term 'OP'. A relatively simple fix would be to give the option for it to be tied to an enchantment. Or that it requires levels and if you run out of levels you have a normal void death.  As a config option it would make all play-style players happy (mostly anyway).

The idea just crossed my mind, so I thought I'd mention it and let you make your choice.  Have a great day, and well done on the mod. I love it <3

**Comment by BlayTheNinth** [comment]
To be honest I don't see the gameplay value added by making it require experience. With the default configurations, it already requires you to be at full health in order to survive, so adding a secondary requirement of "you also have to make sure you always have more than 5 levels of xp" doesn't feel right to me.

Enchantment would work in theory, but in practice 
1) it would make the mod be required on the client
2) it would cause more annoyance by dirtying the enchantment pool (since it would have a chance of going onto every piece of equipment) when you really only ever want to get it once
3) it would require an enchantment table, which by the time you get it you will probably have a pretty secure skyblock base making the mod less necessary

**Comment by MysticAura** [comment]
The problem being that the only complaint I've ever seen of this mod, is
that it takes away all risk without requiring any effort to achieve the
bonus. Either of those suggestions would make it more feasible. Early game
it doesn't really matter much if you die in the void. You do not have
anything much of value to lose anyway. You would be gaining experience very
early in game, just by doing normal things. Requiring a bare minimal amount
of effort in order to earn such rewards isn't a bad thing.
As for the enchantment being required on the client. The packs which the
mod are in are playable single or multiplayer, and would account for a
great many of the downloads. Meaning, they already have the mod client
side. I do understand if you don't want to make this level of effort
though. The experience option may be easier to implement and cleaner.

**Comment by BlayTheNinth** [comment]
My counter points still stand, "this mod is OP because it performs its sole purpose" is not going to cut it. Either use or don't use the mod. Requiring experience points on top of full health is not going to add any gameplay value.

The next version makes the client-side optional meaning you'll be able to easily remove it from servers as well.

**Comment by MysticAura** [comment]
There's nothing wrong with me sharing my perspective. The snarky 'either
use it or don't' wasn't called for. If you don't want to consider ideas,
that's your call. I don't bother offering suggestions with mods I think are
crap (meaning I thought your mod was worth it). I was trying to offer you a
solution so you wouldn't have to deal with as many comments. I apologize
for trying to help when you didn't want any. Have a good day.

**Comment by BlayTheNinth** [comment]
Nothing snarky about it, simple fact. If you want snarky: maybe try not ignoring half of the counter arguments I offer when you're defending your idea.

**Comment by BlayTheNinth** [comment]
To clarify: "use or don't use the mod" was in direct context to the previous sentence. I'm open for suggestions and implement many of them, but they need to fit into the mod and be well designed. I pointed out why your suggestion did not meet that criteria, towards which you simply restated your initial point. I don't like talking to walls either, so I cut it short, not wanting to repeat myself and assuming this to be going nowhere anyways.

So to phrase it again in a less ambiguous manner: if you think the mod is overpowered, don't use it. Forcing a compromise in, just to please those unhappy with the mod's main functionality, is simply not how I go about things. Especially considering that it doesn't make the game more fun in any way, and instead, imposes unexpected criteria on players that they would not be able to grasp without a third party guide book.
